{{- if .Values.build.auth.git.username }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "build.name" . }}-bot-{{ .Release.Namespace }}
  namespace: {{ .Values.tillerNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "build.name" . }}-bot-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "build.name" . }}-bot
  namespace: {{ .Release.Namespace }}
{{- end }}
