apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buildtemplates.build.knative.dev
spec:
  group: build.knative.dev
  names:
    kind: BuildTemplate
    plural: buildtemplates
  scope: Namespaced
  version: v1alpha1