apiVersion: v1
kind: Service
metadata:
  labels:
    role: {{ template "build.webhook.name" . }}
  name: {{ template "build.webhook.name" . }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    role: {{ template "build.webhook.name" . }}