{{- if .Values.build.auth.git.username }}
apiVersion: v1
data:
  password: {{ .Values.build.auth.git.password }}
  username: {{ .Values.build.auth.git.username }}
kind: Secret
metadata:
  name: knative-basic-user-pass
  annotations:
    build.knative.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
{{- end }}
