build:
  controller:
    replicaCount: 1
    image:
      repository: gcr.io/build-crd/github.com/knative/build/cmd/controller@sha256
      tag: 9220968c9aae7e6edac97effc7b693fcf5bbb17edf78aa14347de87b15ac8840
    imagePullPolicy: IfNotPresent
    terminationGracePeriodSeconds: 30
    args:
    - -builder
    - cluster
    - -logtostderr
    - -stderrthreshold
    - INFO
    - -creds-image
    - gcr.io/build-crd/github.com/knative/build/cmd/creds-init@sha256:cfcc14889abe29b54d17ff6cf414918d9d92ff02bb112525742ec2e30117899f
    - -git-image
    - gcr.io/build-crd/github.com/knative/build/cmd/git-init@sha256:d52c29a4a1d83712b048bd32dbb5f97b7d2791af9b892f68fe94e162932ac66e
    resources:
      limits:
      cpu: 200m
      memory: 256Mi
      requests:
      cpu: 100m
      memory: 128Mi
    service:
      type: ClusterIP
      externalPort: 9090
      internalPort: 9090
